font:
  - file: "gfonts://Roboto@700"
    id: font_title
    size: 24
    bpp: 4
    extras:
      - file: "gfonts://Roboto@700"
        glyphs: "°éèêëàâäùûüôöîïçøØ"
  - file: "gfonts://Roboto@500"
    id: font_large
    size: 20
    bpp: 4
    extras:
      - file: "gfonts://Roboto@500"
        glyphs: "°éèêëàâäùûüôöîïçøØ"
      - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
        glyphs: ["\U000F04E6", "\U000F04E8", "\U000F05A9", "\U000F05AA"]
  - file: "gfonts://Roboto"
    id: font_medium
    size: 18
    bpp: 4
    extras:
      - file: "gfonts://Roboto"
        glyphs: "°éèêëàâäùûüôöîïçøØ"
      - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
        glyphs: ["\U000F05A9", "\U000F05AA"]
  - file: "gfonts://Roboto"
    id: font_small
    size: 14
    bpp: 4
    extras:
      - file: "gfonts://Roboto"
        glyphs: "°éèêëàâäùûüôöîïçøØ"
      - file: "https://github.com/Templarian/MaterialDesign-Webfont/raw/master/fonts/materialdesignicons-webfont.ttf"
        glyphs: ["\U000F0142", "\U000F0415", "\U000F04E6", "\U000F04E8", "\U000F05A9", "\U000F05AA"]
  - file: "gfonts://Roboto"
    id: font_tiny
    size: 10
    bpp: 4
    extras:
      - file: "gfonts://Roboto"
        glyphs: "°éèêëàâäùûüôöîïçøØ"
