#!/usr/bin/env python3
"""Generate spoolman_catalog.h from filaments.json + SpoolmanDB.

Reads filaments.json (piitaya/bambu-spoolman-db) for the variant_id ↔ spoolman_id
mapping, then enriches each entry with name + density + spool_weight fetched
from upstream SpoolmanDB. Produces the Spoolman provider catalog header.
"""

import json
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
SPOOLMAN_CATALOG_H = SCRIPT_DIR / "spoolman_catalog.h"

FILAMENTS_JSON_URL = (
    "https://raw.githubusercontent.com/piitaya/bambu-spoolman-db/main/filaments.json"
)
SPOOLMAN_DB_URL = "https://donkie.github.io/SpoolmanDB/filaments.json"
SPOOLMAN_DB_MATERIALS_URL = "https://donkie.github.io/SpoolmanDB/materials.json"

# PLA is the default when no material prefix matches.
FALLBACK_DENSITY = 1.24


def fetch_json(url: str) -> object:
    print(f"Fetching {url}...")
    req = urllib.request.Request(
        url,
        headers={"User-Agent": "bambu-nfc-generator/1.0"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode("utf-8"))


def cpp_escape(s: str) -> str:
    """Escape a string for inclusion in a C++ string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def fetch_spoolman_db() -> dict[str, dict]:
    """Fetch SpoolmanDB and return a dict mapping spoolman_id → metadata."""
    data = fetch_json(SPOOLMAN_DB_URL)
    bambu_entries = {}
    for entry in data:
        eid = entry.get("id", "")
        if not eid.startswith("bambulab_"):
            continue
        bambu_entries[eid] = {
            "name": entry.get("name", ""),
            "density": entry.get("density", 0.0),
            "spool_weight": entry.get("spool_weight", 0),
        }
    print(f"  Found {len(bambu_entries)} Bambu Lab entries in SpoolmanDB")
    return bambu_entries


def fetch_material_densities() -> list[tuple[str, float]]:
    """Fetch materials.json and return (material, density) pairs sorted by
    descending name length, so longest-prefix matching picks e.g. PAHT-CF
    over PA in the C++ lookup."""
    data = fetch_json(SPOOLMAN_DB_MATERIALS_URL)
    pairs: list[tuple[str, float]] = []
    for entry in data:
        material = entry.get("material")
        density = entry.get("density")
        if not material or density is None:
            continue
        pairs.append((material, float(density)))
    pairs.sort(key=lambda p: (-len(p[0]), p[0]))
    print(f"  Loaded {len(pairs)} material density entries")
    return pairs


def generate(
    filaments: list[dict],
    spoolman_db: dict[str, dict],
    materials: list[tuple[str, float]],
) -> str:
    entries = []
    missing_in_db = []
    for f in filaments:
        sid = f.get("spoolman_id")
        if not sid:
            continue
        meta = spoolman_db.get(sid)
        if meta is None:
            missing_in_db.append((f["id"], sid))
            name = f["color_name"]
            density = 0.0
            spool_weight = 0
        else:
            name = meta["name"]
            density = meta["density"]
            spool_weight = meta["spool_weight"]
        entries.append(
            {
                "variant_id": f["id"],
                "spoolman_id": sid,
                "name": name,
                "density": density,
                "spool_weight": spool_weight,
            }
        )

    if missing_in_db:
        print(f"  Warning: {len(missing_in_db)} spoolman_ids not found in SpoolmanDB:")
        for vid, sid in missing_in_db[:5]:
            print(f"    - {vid} -> {sid}")
        if len(missing_in_db) > 5:
            print(f"    ... and {len(missing_in_db) - 5} more")

    lines = [
        "// Generated by generate_spoolman_catalog.py — do not edit manually.",
        "// Source: filaments.json (piitaya/bambu-spoolman-db) + SpoolmanDB",
        "#pragma once",
        "#include <cstdint>",
        "#include <cstring>",
        "",
        "namespace spoolman_catalog {",
        "",
        "struct Entry {",
        "  const char *variant_id;",
        "  const char *spoolman_id;",
        "  const char *name;",
        "  float density;",
        "  uint16_t spool_weight;  // empty spool (cardboard) weight in grams",
        "};",
        "",
        "static const Entry SPOOLMAN_MAP[] = {",
    ]
    for e in entries:
        vid = cpp_escape(e["variant_id"])
        sid = cpp_escape(e["spoolman_id"])
        name = cpp_escape(e["name"])
        density = e["density"]
        spool_weight = int(e["spool_weight"])
        lines.append(
            f'  {{"{vid}", "{sid}", "{name}", {density:.2f}f, {spool_weight}}},'
        )
    lines += [
        "};",
        "",
        f"static const size_t SPOOLMAN_MAP_COUNT = {len(entries)};",
        "",
        "inline const Entry *find(const char *variant_id) {",
        "  for (size_t i = 0; i < SPOOLMAN_MAP_COUNT; i++) {",
        "    if (strcmp(SPOOLMAN_MAP[i].variant_id, variant_id) == 0)",
        "      return &SPOOLMAN_MAP[i];",
        "  }",
        "  return nullptr;",
        "}",
        "",
        "// Material density fallback, sorted most-specific-first so that a",
        "// longest-prefix match on the material name (e.g. PAHT-CF → PAHT)",
        "// returns the closest family density.",
        "struct MaterialDensity {",
        "  const char *prefix;",
        "  float density;",
        "};",
        "",
        "static const MaterialDensity MATERIAL_DENSITIES[] = {",
    ]
    for name, density in materials:
        lines.append(f'  {{"{cpp_escape(name)}", {density:.2f}f}},')
    lines += [
        "};",
        "",
        f"static const size_t MATERIAL_DENSITIES_COUNT = {len(materials)};",
        f"static constexpr float MATERIAL_DENSITY_FALLBACK = {FALLBACK_DENSITY:.2f}f;",
        "",
        "inline float material_density(const char *material) {",
        "  if (material == nullptr) return MATERIAL_DENSITY_FALLBACK;",
        "  for (size_t i = 0; i < MATERIAL_DENSITIES_COUNT; i++) {",
        "    const char *prefix = MATERIAL_DENSITIES[i].prefix;",
        "    if (strncmp(material, prefix, strlen(prefix)) == 0)",
        "      return MATERIAL_DENSITIES[i].density;",
        "  }",
        "  return MATERIAL_DENSITY_FALLBACK;",
        "}",
        "",
        "}  // namespace spoolman_catalog",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    filaments = fetch_json(FILAMENTS_JSON_URL)
    print(f"  Loaded {len(filaments)} filament entries")

    spoolman_db = fetch_spoolman_db()
    materials = fetch_material_densities()

    print(f"Writing {SPOOLMAN_CATALOG_H}...")
    SPOOLMAN_CATALOG_H.write_text(generate(filaments, spoolman_db, materials))
    print("Done.")


if __name__ == "__main__":
    main()
