#!/usr/bin/env python3
"""Generate filaments.h from filaments.json — display layer only.

Reads filaments.json (piitaya/bambu-spoolman-db format) and produces a C++
header mapping variant_id → color_name. This is the provider-agnostic display
layer used by the reader UI.
"""

import json
import urllib.request
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent
FILAMENTS_H = SCRIPT_DIR / "filaments.h"

FILAMENTS_JSON_URL = (
    "https://raw.githubusercontent.com/piitaya/bambu-spoolman-db/main/filaments.json"
)


def fetch_filaments() -> list[dict]:
    print(f"Fetching {FILAMENTS_JSON_URL}...")
    req = urllib.request.Request(
        FILAMENTS_JSON_URL,
        headers={"User-Agent": "bambu-nfc-generator/1.0"},
    )
    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read().decode("utf-8"))


def cpp_escape(s: str) -> str:
    """Escape a string for inclusion in a C++ string literal."""
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate(filaments: list[dict]) -> str:
    lines = [
        "// Generated by generate_filaments.py — do not edit manually.",
        "// Source: filaments.json (piitaya/bambu-spoolman-db)",
        "#pragma once",
        "#include <cstring>",
        "#include <string>",
        "",
        "namespace filaments {",
        "",
        "struct Entry {",
        "  const char *id;",
        "  const char *color_name;",
        "};",
        "",
        "static const Entry FILAMENTS[] = {",
    ]
    for f in filaments:
        fid = cpp_escape(f["id"])
        name = cpp_escape(f["color_name"])
        lines.append(f'  {{"{fid}", "{name}"}},')
    lines += [
        "};",
        "",
        f"static const size_t FILAMENTS_COUNT = {len(filaments)};",
        "",
        "// Returns the color_name if found, otherwise the variant_id itself (display fallback).",
        "inline std::string color_name_for(const char *variant_id) {",
        "  for (size_t i = 0; i < FILAMENTS_COUNT; i++) {",
        "    if (strcmp(FILAMENTS[i].id, variant_id) == 0)",
        "      return FILAMENTS[i].color_name;",
        "  }",
        "  return std::string(variant_id);",
        "}",
        "",
        "}  // namespace filaments",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    filaments = fetch_filaments()
    print(f"  Loaded {len(filaments)} filament entries")

    print(f"Writing {FILAMENTS_H}...")
    FILAMENTS_H.write_text(generate(filaments))
    print("Done.")


if __name__ == "__main__":
    main()
