lvgl:
  displays:
    - my_display
  touchscreens:
    - my_touchscreen
  disp_bg_color: 0x111111
  disp_bg_opa: COVER
  style_definitions:
    - id: style_page
      bg_color: 0x111111
      bg_opa: COVER
      border_width: 0
      scrollbar_mode: "OFF"
    - id: style_text_primary
      text_color: 0xFFFFFF
      text_font: font_large
      text_align: CENTER
    - id: style_text_secondary
      text_color: 0x888888
      text_font: font_medium
      text_align: CENTER
    - id: style_btn_dark
      radius: 12
      bg_color: 0x2D2D2D
      bg_opa: COVER
      border_width: 0
      pad_left: 14
      pad_right: 14
      pad_top: 0
      pad_bottom: 0
      scrollbar_mode: "OFF"
    - id: style_btn_outline_green
      radius: 12
      bg_color: 0x111111
      bg_opa: COVER
      border_width: 2
      border_color: 0x00AE42
      pad_all: 0
      scrollbar_mode: "OFF"
    - id: style_separator
      bg_color: 0x333333
      bg_opa: COVER
      border_width: 0
      scrollbar_mode: "OFF"
    - id: style_detail_row
      bg_opa: TRANSP
      border_width: 0
      pad_all: 0
      scrollbar_mode: "OFF"
