esphome:
  name: bsb-proxy
  friendly_name: BSB Proxy
  min_version: 2026.4.0
  name_add_mac_suffix: false

esp32:
  variant: esp32
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret bsb_proxy_api_encryption_key

# Allow Over-The-Air updates
ota:
  - platform: esphome
    password: !secret bsb_proxy_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none # avoid modem-sleep latency on the bus