substitutions:
  name: lecteur-de-filament-2
  friendly_name: Lecteur de filament 2

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:

api:
  encryption:
    key: !secret lecteur_de_filament_2_api_encryption_key

ota:
  - platform: esphome
    password: !secret lecteur_de_filament_2_ota_password

packages:
  wifi: !include common/wifi.yaml
  board: !include lecteur_de_filament_2/board.yaml
  display: !include lecteur_de_filament_2/display.yaml
  fonts: !include lecteur_de_filament_2/fonts.yaml
  nfc: !include lecteur_de_filament_2/nfc.yaml
  ui: !include lecteur_de_filament_2/ui.yaml
