substitutions:
  name: lecteur-de-filament
  friendly_name: Lecteur de filament

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:

api:
  encryption:
    key: !secret lecteur_de_filament_api_encryption_key

ota:
  - platform: esphome
    password: !secret lecteur_de_filament_ota_password

packages:
  wifi: !include common/wifi.yaml
  board: !include lecteur-de-filament/board.yaml
  power: !include lecteur-de-filament/power.yaml
  display: !include lecteur-de-filament/display.yaml
  fonts: !include lecteur-de-filament/fonts.yaml
  nfc: !include lecteur-de-filament/nfc.yaml
  bss: !include lecteur-de-filament/bambu_spoolman_sync.yaml
  styles: !include lecteur-de-filament/styles.yaml
  page_idle: !include lecteur-de-filament/page_idle.yaml
  page_filament: !include lecteur-de-filament/page_filament.yaml
  page_details: !include lecteur-de-filament/page_details.yaml
  triggers: !include lecteur-de-filament/triggers.yaml
